### PR TITLE
add g.. alias

### PR DESCRIPTION
**Pull request by Eriner**

### CODE REVIEW

**Comment by cgundogan** [comment]
#974, please link to previous PRs if you are proposing alternative ones

**Comment by Eriner** [comment]
You are correct, I knew I got that from somewhere, but in my late-night stupor, searching for 'g..' came up with nothing.

**Comment by Eriner** [comment]
@cgundogan I will close this PR, that said, I would ask to have `g..` be considered over `grt`, as it is more intuitive.

**Comment by Eriner** [comment]
Yes, you are correct. I thought I had seen this someplace, but in my late-night stupor I didn't find anything while searching 'g..'

On November 2, 2015 5:21:16 AM EST, "Cenk Gündoğan" <notifications@github.com> wrote:
>#974, please link to previous PRs if you are proposing alternative ones
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sorin-ionescu/prezto/pull/1017#issuecomment-152979069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
