### PR TITLE
Add some new git aliases, modify a few more.

### PR DESCRIPTION
**Pull request by malikoth**
# Additions
- Add `gbV` command to show more verbose git branch info.
- Add `gcam` to make it possible to execute `gca; gcm '<your message
  here>'` more simply.
- Add `gii` command to temporarily untrack (ignore) a file.
- Add `giI` command to uningore a file.
# Modifications
- Change alias of `gbl` to `gbv`. Personally, I think aliases that
  include a switch in the command should include the switch in the alias
  if possible.  This makes them easier to remember.
- Change alias of `gbL` to `gba`. I think the `-a` switch is more
  salient to what this alias does than the `-v`.  Furthermore, with this
  PR there are already `gbv` and `gbV` aliases, so those are out.
- Change implementation of `gCl` alias to use built-in capabilities of
  git, rather than sed.

Please, let me know what you like, and what I should have left well-enough alone.  :D  I'm not married to any of the changes here.  What I started this PR for was to include the `gii` and `giI` commands.  I made a few other changes I'd like to see, that I think make git aliases more consistent, but I would happily back them out to get my two commands in.

### CODE REVIEW

**Comment by malikoth** [comment]
Also @sorin-ionescu I see a ton of open PRs, some of which I would very much like to see merged in the near future.  Is there anything I could do to help out with the project?

**Comment by belak** [comment]
I'm not sure what the best way forward for this is... I'd like to avoid the alias hell that's seen in oh-my-zsh, but some of these could be useful... does anyone else have opinions on this, or is it just me?

**Comment by belak** [comment]
Ok, I merged a way of disabling git aliases in a separate PR, so if you're willing to rebase against that I can take another look at this.

**Comment by wadkar** [comment]
you know, if you could update this PR with my #1107 , I will close that PR and we can put our effort together to help and get this PR merged.

**Comment by malikoth** [comment]
In the past, I got impatient with the lack of activity in this repo, and deleted my fork.  Since I have no way to modify this PR.  I have created a new PR at https://github.com/sorin-ionescu/prezto/pull/1301 and rebased it off of the current master.

@wadkar Keep your PR open.  @belak will merge it shortly.  He already said he likes your PR, he'll get to it.  There's no reason to move your PR to another PR.

**Pull request closed without merging**
