### PR TITLE
git performance improvement if aliased

### PR DESCRIPTION
**Pull request by teemow**
If git is aliased to hub the performance of the git module was very poor. The prompt was very laggy. 

I replaced all occurences of `git` with `command git` and used it for a while now. Performance is back to normal and all git infos are displayed nicely.

### CODE REVIEW

**Comment by ianks** [comment]
Slightly off topic, but if you install hub from --HEAD performance is much better as it is written in Go.

**Comment by sorin-ionescu** [comment]
This is a duplicate of #462.

**Comment by belak** [comment]
This still seems like a reasonable change. Is there any reason to avoid merging this @sorin-ionescu ?

**Comment by belak** [comment]
Unfortunately, there are pretty substantial conflicts in this now. If you'd still like this to be merged, please re-submit it rebased off of the master branch.

**Pull request closed without merging**
