### PR TITLE
prompt: update powerlevel10k submodule to v1.3.0

### PR DESCRIPTION
**Pull request by romkatv**
Release notes: https://github.com/romkatv/powerlevel10k/releases/tag/v1.3.0

### CODE REVIEW

**Comment by belak** [comment]
It blows my mind how you're able to get these out so quickly. Thanks for submitting this!

**Comment by jeffwidman** [comment]
Looks like I need to block some time on my calendar to explore this theme.

**Comment by romkatv** [comment]
> Looks like I need to block some time on my calendar to explore this theme.

It's not the worst 😉

**Comment by wadkar** [comment]
I am looking forward to [.purepower config](https://github.com/romkatv/dotfiles-public/blob/2d27deefd928175b80d681fc06eb2791848591fd/.purepower) making a comeback.

The powerline rendering gets boring after a while, if you ask me. Too much noise after you get used to the prompt elements and there locations.

**Comment by romkatv** [comment]
> I am looking forward to [.purepower config](https://github.com/romkatv/dotfiles-public/blob/2d27deefd928175b80d681fc06eb2791848591fd/.purepower) making a comeback.

You can still use this config. Just like all p10k configs, it still works and will keep working forever. *Lean* style is better though.

**Comment by wadkar** [comment]
Ah, just switched to _Lean_ style with`p10k configure` and I quite like it, thanks!

**Pull request merged**
