### PR TITLE
Runcoms doc

### LINKED ISSUE #1535: easy way for prezto customization
`git pull` is great, but maybe add workflow for more easy prezto customization, like add in .zshrc:
```shell
if [ -f ~/.zshrc.local ]; then
    . ~/.zshrc.local
fi
```

### PR DESCRIPTION
**Pull request by hlecuanda**
Please be sure to check out our [contributing guidelines](https://github.com/sorin-ionescu/prezto/blob/master/CONTRIBUTING.md)
before submitting your pull request.

Fixes #1535 

## Proposed Changes

  - Detailed documentation for runcoms
  - Discussion about the most common pitfalls
  
(no screenshot available, it is a repo Markdown file...

### CODE REVIEW

**Comment by hlecuanda** [comment]
:thinking: uh.. not sure how my upstream syncs got in there, only https://github.com/sorin-ionescu/prezto/pull/1537/commits/ede94a9caeade863afe01272b25a8b5d72eb1a3c should be there. if someone can tell me how to fix this i'll happily do it to have a neat merge...

**Comment by diraol** [comment]
Hum.... that's a little bit messy.... but may be you can do something like the following to keep using the same branch:

```
git stash save 'before mess'
git checkout runcoms-doc
git reset HEAD~6
git rebase sorin-ionescu master
git cherry-pick 
git commit ede94a9caeade863afe01272b25a8b5d72eb1a3c
git push -f
git stash pop
```

With this I THINK you will discard the previous 5 commits and keep the last one.

Using `git push -f` is always risky, so do it on your own risk!

**Comment by hlecuanda** [comment]
thx... ill do that or start from a fresh tree.. lucky the intended changes are pretty straightforward on a single file... =) i'll close this PR and resubmit. Thx again

**Comment by hlecuanda** [comment]
Thanks, @diraol ! i've now submitted https://github.com/sorin-ionescu/prezto/pull/1540 which should be clean. =)

**Pull request closed without merging**
