### PR TITLE
Add WD module from oh-my-zsh to prezto

### PR DESCRIPTION
**Pull request by mtxr**
This modules is really helpful for me and I think more people would like to use it.

### CODE REVIEW

**Comment by mtxr** [comment]
Please, include his README file.

https://github.com/mfaerevaag/wd

**Comment by sorin-ionescu** [comment]
This must be implemented as an external module. See history-substring-search for an example.

**Comment by PaBLoX-CL** [comment]
How is that this is more useful than using `fasd` and `pushd`/`popd`. I don't understand :/

**Comment by sorin-ionescu** [comment]
I don't understand either.

**Pull request closed without merging**
