### PR TITLE
prompt: update powerlevel10k submodule to v1.14.3

### PR DESCRIPTION
**Pull request by romkatv**
Release notes:

- https://github.com/romkatv/powerlevel10k/releases/tag/v1.14.0
- https://github.com/romkatv/powerlevel10k/releases/tag/v1.14.1
- https://github.com/romkatv/powerlevel10k/releases/tag/v1.14.2
- https://github.com/romkatv/powerlevel10k/releases/tag/v1.14.3

### CODE REVIEW

**Comment by melgu** [comment]
Please merge. It potentially fixes issues on Silicon Macs running Big Sur.

**Comment by romkatv** [comment]
> Please merge. It potentially fixes issues on Silicon Macs running Big Sur.

It does. From release notes:

> Support Apple Silicon (Darwin arm64).

**Comment by jonBoone** [comment]
Yes, please merge.  gitstatus is not working on my Apple Silicon M1 running Big Sur with p10k theme.  I really love this theme...

prezto is 👍

**Comment by billinghamj** [comment]
@sorin-ionescu @belak Possible this could be looked at this week?

**Comment by billinghamj** [comment]
Also maybe @romkatv could be added as a maintainer? Seems a pretty high proportion of the commits these days are p10k being updated - otherwise the project is fairly dormant anyway.

**Comment by romkatv** [comment]
Thanks, @belak !

**Comment by belak** [comment]
Thanks for the ping - I must have missed this.

@billinghamj This was [brought up before](https://github.com/sorin-ionescu/prezto/issues/1269#issuecomment-553993438), but romkatv respectfully declined. Also, at the moment Sorin is still the only person who has admin access to this repo, so we're dependent on him to add collaborators.

**Comment by romkatv** [comment]
> @billinghamj This was [brought up before](https://github.com/sorin-ionescu/prezto/issues/1269#issuecomment-553993438), but romkatv respectfully declined.

Right. It may look like I'm responsible for a large share of commits to prezto but there is no code in them. All my PRs are one line changes devoid of code. They just move the commit hash for powerlevel10k submodule.

**Comment by belak** [comment]
Yep, I respect your position. I mostly wanted to have you added so you could make those one-line changes without needing to wait for anyone. My reply was just an unsent one (from two days ago that I found in a tab) aiming to clear that up. :)

**Pull request merged**
