### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jeffwidman**

### CODE REVIEW

**Comment by indrajitr** [comment]
@jeffwidman, we usually don't do merge commit in prezto. I am guessing it was unintentional :)

**Comment by jeffwidman** [comment]
I'm sorry, what is the normal workflow here?

I was added as a collaborator a while back, and just hadn't had time to contribute much. 

When I saw the typo, I thought I'd just fix it, created a PR for review then decided why waste someone else's time when it was such a small fix, so just merged it directly...

Definitely appreciate you pointing me in the right direction.

**Comment by indrajitr** [comment]
> I'm sorry, what is the normal workflow here?
> I was added as a collaborator a while back, and just hadn't had time to contribute much.

Absolutely no issues, my friend. Thank you for taking opportunity to collaborate as and when time permits.

> When I saw the typo, I thought I'd just fix it, created a PR for review then decided why waste someone else's time when it was such a small fix, so just merged it directly...

That's totally fine. @belak and I do this often for trivial PRs.

> Definitely appreciate if you can point me in the right direction on workflow, do you normally merge PR's via rebase?

We don't really have a stringent workflow to be honest. It is mostly a continuation of how @sorin-ionescu used to operate.
Just basic stuff:
* Trivial fixes (or breaking changes) don't necessarily need to wait for PR cycle (e.g., #1398 or 2db7f62 for #1386 etc.)
* Non trivial changes are discussed and vetted before going in (e.g., #1385)
* Avoid merge commit and do rebase commit instead. We do "Rebase and merge" (the default one) instead of "Create a merge commit" as so:
screen shot 2017-07-25 at 1 26 02 pm

**Comment by jeffwidman** [comment]
Sounds good. I will do my best to follow this. 

I help out on a lot of other github-based projects, so generally pretty familiar with how things work, although occasionally I forget which projects prefer merge commits and which prefer rebasing. But for a bit here I might just help out on the issue tracker and code reviews but refrain from merging until I get used to the style around here.

**Pull request merged**
