### PR TITLE
Make git checkout more quickly than normal git clone

### PR DESCRIPTION
**Pull request by netroby**
Make git checkout more quickly than normal git clone

using git clone --depth=1 to clone faster than normal full clone

### CODE REVIEW

**Comment by PaBLoX-CL** [comment]
This doesn't make sense since Sorin has stated that the idea of prezto **is** to be managed by git... why would you want to have only part of the history?

**Comment by netroby** [comment]
I am not want to get the full history. i just want let it working. not download full repo , waste disk space.

**Comment by sorin-ionescu** [comment]
Prezto cloned with `--depth 1` takes the same amount of disk space.

**Comment by netroby** [comment]
I made a test with linux kernel 

```
[netroby@localhost oss]$ git clone --depth 1 https://github.com/torvalds/linux linux-d1
正克隆到 'linux-d1'...
remote: Counting objects: 51811, done.
remote: Compressing objects: 100% (50319/50319), done.
remote: Total 51811 (delta 3742), reused 11860 (delta 856), pack-reused 0
接收对象中: 100% (51811/51811), 139.22 MiB | 1.06 MiB/s, 完成.
处理 delta 中: 100% (3742/3742), 完成.
检查连接... 完成。
正在检出文件: 100% (48948/48948), 完成.
[netroby@localhost oss]$ git clone --depth=1 https://github.com/torvalds/linux linux-d2
正克隆到 'linux-d2'...
remote: Counting objects: 51811, done.
remote: Compressing objects: 100% (50319/50319), done.
^C收对象中:  10% (5182/51811), 8.32 MiB | 931.00 KiB/s     
[netroby@localhost oss]$ git clone  https://github.com/torvalds/linux linux-d3
正克隆到 'linux-d3'...
remote: Counting objects: 4043526, done.
remote: Compressing objects: 100% (23/23), done.
^C收对象中:   1% (57592/4043526), 22.95 MiB | 1.54 MiB/s 
```

**Comment by netroby** [comment]
```
[netroby@localhost oss]$ git clone --depth=1 https://github.com/sorin-ionescu/prezto.git p1
正克隆到 'p1'...
remote: Counting objects: 211, done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 211 (delta 7), reused 68 (delta 4), pack-reused 0
接收对象中: 100% (211/211), 96.69 KiB | 0 bytes/s, 完成.
处理 delta 中: 100% (7/7), 完成.
检查连接... 完成。

```
96.69 Kb 


```
[netroby@localhost oss]$ git clone  https://github.com/sorin-ionescu/prezto.git p2
正克隆到 'p2'...
remote: Counting objects: 8479, done.
remote: Total 8479 (delta 0), reused 0 (delta 0), pack-reused 8479
接收对象中: 100% (8479/8479), 1.68 MiB | 613.00 KiB/s, 完成.
处理 delta 中: 100% (3747/3747), 完成.
检查连接... 完成。

```
1.68 MB

**Comment by netroby** [comment]
@sorin-ionescu  can you check your test result again? 
I really do lot's of test to confirm it.

**Comment by sorin-ionescu** [comment]
I checked. You are right. Nevertheless, I am not merging it. It's up to the users who care to do this. Prezto is not LINUX. It does not take much disk space. The history is useful to reveal when bugs were introduced.

**Comment by netroby** [comment]
That's fine, thanks for your time.

**Pull request closed without merging**
