### PR TITLE
Fix typo in dnf module README

### PR DESCRIPTION
**Pull request by ryansb**

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
I must have been thinking of cheese. Thanks.

It's also in the [yum](https://github.com/sorin-ionescu/prezto/blob/master/modules/yum/README.md) module.

**Comment by ryansb** [comment]
@sorin-ionescu ping? Would it be possible to merge this?

**Comment by ryansb** [comment]
@sorin-ionescu hi, would it be possible to get this merged? It's a pretty small fix.

**Comment by Eriner** [comment]
@ryansb project seems to have been near-abandoned by @sorin-ionescu.

**Comment by sorin-ionescu** [comment]
@Eriner It's not abandoned.

**Comment by Eriner** [comment]
Tell that to this 5 month-old 2-line PR.

**Comment by sorin-ionescu** [comment]
Neglected, not abandoned. I use Prezto. I can't abandon that which I use.

**Comment by msoucy** [comment]
Looks abandoned to me. No commits to master in five months?

**Comment by Eriner** [comment]
@msoucy if you want a repo with many of the valid PRs merged, I've been merging them in my fork.

**Comment by sorin-ionescu** [comment]
@Eriner Open PR requests. I'll start merging again next week.

**Comment by Eriner** [comment]
@sorin-ionescu I've made a fair few, but I need to head to bed. I will PR the debug module I made after things start being pulled. Thanks :+1:

**Comment by ryansb** [comment]
Uh....ok.

**Comment by jeffwidman** [comment]
For anyone else curious why this was closed, it was because it was actually pulled in via this commit: https://github.com/sorin-ionescu/prezto/commit/02b3d329acdef10c145a1068e9f2a419d8104444 and GitHub's UI isn't smart enough to figure that out.

**Pull request closed without merging**
