### PR TITLE
Also lookup on ~/.ssh/config.d/* files when doing ssh host complete

### PR DESCRIPTION
**Pull request by rjcoelho**
Because I use
Include ~/.ssh/config.d/*
on my ~/.ssh/config

Anyone knows how to put this into a SSH_CONFIG env var ?

### CODE REVIEW

**Comment by indrajitr** [comment]
We probably have to scan `Include` in `~/.ssh/config` instead of blindly assuming `~/.ssh/config.d/*`. What do you think @rjcoelho?

**Comment by rjcoelho** [comment]
> We probably have to scan `Include` in `~/.ssh/config` instead of blindly assuming `~/.ssh/config.d/*`. What do you think @rjcoelho?

It's going to slow down the startup time, plus it doesn't really change on every login. Its something done once on "setup". How about an env var SSH_CONFIG=~/.ssh/config.d/* ?

**Comment by indrajitr** [comment]
> > We probably have to scan `Include` in `~/.ssh/config` instead of blindly assuming `~/.ssh/config.d/*`. What do you think @rjcoelho?
> 
> It's going to slow down the startup time, plus it doesn't really change on every login. Its something done once on "setup". How about an env var SSH_CONFIG=~/.ssh/config.d/* ?

Hmm, let me think about this a bit more. I'm hesitant to add yet another magic environment variable.

If at all, `zstyle` based configuration would be preferred instead of an environment variable.

**Comment by rjcoelho** [comment]
> > > We probably have to scan `Include` in `~/.ssh/config` instead of blindly assuming `~/.ssh/config.d/*`. What do you think @rjcoelho?
> > 
> > 
> > It's going to slow down the startup time, plus it doesn't really change on every login. Its something done once on "setup". How about an env var SSH_CONFIG=~/.ssh/config.d/* ?
> 
> Hmm, let me think about this a bit more. I'm hesitant to add yet another magic environment variable.
> 
> If at all, `zstyle` based configuration would be preferred instead of an environment variable.

Yes I agree, since AFAIK zstyle is the preferred way of configuring in zsh. Anyone knows how to do it using zstyle ?

**Comment by diraol** [comment]
Hey folks, not sure if this has happened or will happen somewhere in the future, but I just want to add to the discussion that while using `Include` I usually have multiple config files separated across many different paths (I do it for gitconfig too), one for each "context".

So, for each independent project I'm part of I usually have a `~/.<project>` path with configs for it (gitconfig, ssh, aliases, env vars, etc).

So, if we are going with zstyle config, it would be nice to have the ability to setup multiple paths.

**Comment by srijanshetty** [comment]
Having `Include config.d/*` as the first line on my `.ssh/config` automatically completes all the hosts present in `config.d/*`.

**Comment by srijanshetty** [comment]
> Hey folks, not sure if this has happened or will happen somewhere in the future, but I just want to add to the discussion that while using `Include` I usually have multiple config files separated across many different paths (I do it for gitconfig too), one for each "context".
> 
> So, for each independent project I'm part of I usually have a `~/.<project>` path with configs for it (gitconfig, ssh, aliases, env vars, etc).
> 
> So, if we are going with zstyle config, it would be nice to have the ability to setup multiple paths.

I have a similar setup but I symlink all files to `.ssh/config.d/` and autocomplete works automatically.

**Comment by srijanshetty** [comment]
Closing this as zsh supports Include directive natively [now](https://github.com/zsh-users/zsh/commit/5ded0ad96740b62ea0214387ee260b515726a05e).

**Pull request closed without merging**
