### PR TITLE
Adding zaw as an external module

### PR DESCRIPTION
**Pull request by santiycr**
Including some default settings + possibilities to customize highlighting via a properly spaced zstyle

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
All bugs have been closed, except for the [multiline history rendering bug](https://github.com/zsh-users/zaw/issues/17). 

Usually, the commands that I want from history are multiline since those are the ones that are long and I do not wish to retype. This bug makes zaw-history useless for me.

I'll keep an eye on it.

**Comment by excetara2** [comment]
I am interested to give a zaw a try with prezto. Have you looked at this any closer? Do you have a newer branch with zaw or the newest is still the one posted from two years ago above? Just asking because I've seen the multiline rendering bug has been fixed.

**Comment by santiycr** [comment]
multiline continues to work only by rendering new lines via `\n` all into a single line. I never minded that and have been using zaw through my fork of prezto for years:
https://github.com/sorin-ionescu/prezto/compare/master...santiycr:master

**Comment by brandon-fryslie** [comment]
You can use [zgen](https://github.com/tarjoilija/zgen) to enable zaw with prezto.  Put this in your .zshrc file where you define your zgen configuration:

```shell
zgen load zsh-users/zaw
bindkey '^X' zaw
```

You can enable other options as needed by following the zaw documentation.

**Pull request closed without merging**
