### PR TITLE
Add depth to clone command

### PR DESCRIPTION
**Pull request by steelbrain**
Not everyone wants the whole history of the repo

[Review on Reviewable](https://reviewable.io/reviews/sorin-ionescu/prezto/941)

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
That's user preference.

**Comment by steelbrain** [comment]
The majority of the users, including myself wouldn't want the history of the repo, and I haven't come across a single user-case, mind telling me one? :)

**Comment by sorin-ionescu** [comment]
You're projecting your preference onto everyone. You're the second person to request this in the many years this project has existed.

**Comment by steelbrain** [comment]
Forgive me if my question was unclear, but I was asking about why would the users need the history of the repo?

**Comment by sorin-ionescu** [comment]
He who wants to contribute to its development, which I encourage, needs the history.

**Comment by steelbrain** [comment]
Users don't need the whole history of the repo, and this repo has 190 contributors and 4603 stars,
and even contributors can just branch from the latest commit and contribute, If they need whole git history, we have github web interface for it.

**Pull request closed without merging**
