### PR TITLE
Add `-` alias for `cd -`

### PR DESCRIPTION
**Pull request by Enzime**
Taken with love from `oh-my-zsh`

### CODE REVIEW

**Comment by Enzime** [comment]
@belak @indrajitr any thoughts on this PR?

**Comment by indrajitr** [comment]
I like it 🤣. But I want to have @belak, @jeffwidman and others weigh in to see if this aligns with general aesthetics of prezto.

**Comment by Enzime** [comment]
@sorin-ionescu @indrajitr any thoughts on this PR?

**Comment by sorin-ionescu** [comment]
Using dashes for an alias might cause problems. Are there any known conflicts?

**Comment by Enzime** [comment]
I think this should be low risk as `ohmyzsh` has had this alias for 13 years now and I'm not aware of any issues.

This alias should only have an effect when someone uses a single dash as a command i.e.
```
$ -
$ - apple
```

The only conflict I'm aware of is a `zsh` builtin for `-` which does the following:

``The  command  is  executed  with  a `-' prepended to its argv[0] string.``

**Review by jeffwidman — APPROVED** [review]
👍 from me.

**Comment by belak** [comment]
Looks good to me! Thanks!

**Pull request merged**
