### PR TITLE
Fix English mistakes in the autosuggestions module README.md

### LINKED ISSUE #1441: Ambiguous pronouns in module READMEs
### Description

In module READMEs, some pronouns may be ambiguous. For example, in the [autosuggestions module](https://github.com/sorin-ionescu/prezto/tree/master/modules/autosuggestions)'s README.md:

> If this module is used in conjuncture with the syntax-highlighting module, it must be loaded after it.

Some people may not be able to tell what the first 'it' refers to.
For example, does the sentence mean:

> If this module is used in conjuncture with the syntax-highlighting module, this module must be loaded after it.

Or is the sentence supposed to mean:

> If this module is used in conjuncture with the syntax-highlighting module, it must be loaded after this module.

Fixing this issue will minimize confusion and prevent configuration mistakes.

### PR DESCRIPTION
**Pull request by foochuanwei**
Fixes #1441 

## Proposed Changes
* Fix English mistakes in the README.md of the autosuggestions module:
⋅⋅* Fix the incorrect use of 'conjuncture' by replacing it with 'conjunction'.
⋅⋅* Fix ambiguous pronoun references.

### CODE REVIEW

**Comment by belak** [comment]
Thanks for your contribution! Looks good.

**Comment by sergiorussia** [comment]
@foochuanwei your fix now confuses me. previously i read it like "put autosuggestions AFTER syntax-highlighting and history-substring-search" and changed my config accordingly. now after your edit it reads like "put autosuggestions BEFORE syntax-highlighting and history-substring-search". what is the correct version?

**Comment by sergiorussia** [comment]
this is how ppl like me read previous version:
If this module is used in conjuncture with the X module, it (this module) must be loaded **after** it (X module).

**Comment by sergiorussia** [comment]
yeah, look at https://github.com/zsh-users/zsh-history-substring-search/tree/aae3388491c2312c4efb2e86bcb999927bb2900e, it states that history-substring-search should be loaded after syntax-highlighting. and as i mentioned above, doc says exactly that. in other words the PR is wrong, autosuggestions should be loaded after both modules, **not** before.

**Pull request merged**
