### PR TITLE
feat: Update submodules to avoid error with using zsh 5.9

### LINKED ISSUE #2061: Using module `syntax-highlighting` show an error "maximum nested function level reached"
### Description
Loading Prezto module `modules/syntax-highlighting`  with `zsh` version 5.9 shows an error message "maximum nested function level reached".

### Expected behavior
No error message is expected.

### Actual behavior
After configuration, the following error message is shown.

```sh
~/.zprezto master*
❯ ls
_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
modules  runcoms  CONTRIBUTING.md  LICENSE  README.md  init.zsh
```

#### 1. Install Zsh 5.9

Install zsh 5.9 by following procedure:

```sh
wget https://sourceforge.net/projects/zsh/files/zsh/5.9/zsh-5.9.tar.xz/download -O zsh-5.9.tar.xz
tar xvf zsh-5.9.tar.xz 
cd zsh-5.9/
./configure --enable-multibyte
make
sudo make install
```

#### 2. Install Prezto

Insstall Prezto by following, the very standard procedure:

https://github.com/sorin-ionescu/prezto#installation

#### 3. Edit `.zpreztorc`

First add two lines as follows:

```txt
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'history-substring-search' \
+  'syntax-highlighting' \
+  'autosuggestions' \
  'prompt'
```

And the setting of prompt theme to load is changed as follows:

```txt
# Set the prompt theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
- zstyle ':prezto:module:prompt' theme 'sorin'
+ zstyle ':prezto:module:prompt' theme 'pure'
```

### Versions

  - Prezto commit: 5ac930d96be3a51730f7d9d7330f28d9c9c36e0a
  - ZSH version: 5.9
  - OS information: Ubuntu 22.04.2 LTS, on WSL2

### PR DESCRIPTION
**Pull request by ntnamazu**
Fixes #2061 

## Proposed Changes

- Just update submodules of `modules/`.
- This update resolved error message (an issue #2061) at my local environment.

### CODE REVIEW

**Review by jeffwidman — APPROVED** [review]
Thanks!

**Comment by indrajitr** [comment]
@jeffwidman: Was this PR vetted/tested to see if the actual issue was fixed? Quite a few of the submodule updates look arbitrary to me:
- powerlevel10k (this is extremely well maintained and usually @romkatv makes PR when there is a release, this PR doesn't seem to pickup any specific release tag)
- async (this is picking up a spurious github workflow change, nothing else)
- zsh-completion (this is also well maintained and we usually pickup a tagged version, not an arbitrary one)
- autosuggestion (again, no useful change other than doc changes)
- zsh-syntax-highlighting (again this is an untagged version - I don't have any concern picking up a non-tagged version if this actually solves a known issue, but without a reasonable justification, this looks arbitrary)

**Comment by jeffwidman** [comment]
Good point, I should have asked it to be slimmed down to the one that fixed the bug and move the others to separate PRs. TBH I completely forgot about waiting for tagged releases of submodules, but completely agree with you that it's a better way assuming upstream tags releases. Going forward I'll try to remember.

**Comment by romkatv** [comment]
> powerlevel10k (this is extremely well maintained and usually @romkatv makes PR when there is a release, this PR doesn't seem to pickup any specific release tag)

Thank you for spotting this! Indeed, powerlevl10k in prezto always tracks the latest release. I'm updating the submodule reference on the same day when I cut a new release.

**Pull request merged**
