### PR TITLE
Add external module bd.

### PR DESCRIPTION
**Pull request by eugenk**
Since #741 was rejected because it was not a submodule, I made it a submodule now.

### CODE REVIEW

**Comment by eugenk** [comment]
Any new opinions on this pull request?

**Comment by sorin-ionescu** [comment]
Apparently not.

**Comment by eugenk** [comment]
What about the old opinions? You said, you wanted this to be an external module (which it is now) and that you don't see much use in this. However, there were some +1 comments in the old pull request, telling what the use is. Are you still against `bd`?

**Comment by zmwangx** [comment]
@eugenk I find `bd` pretty useful, thanks for the good work. But honestly, one shouldn't argue with the maintainer. Folks can merge this into their own forks if they like it; for instance, I just merged this PR into my own fork: https://github.com/zmwangx/prezto/commit/a50d4d35f925f3f7566b7b5fe8f9aea822b4e43b.

**Comment by eugenk** [comment]
Don't get me wrong, I don't want to argue. Sorry if I came off that way. There was just no comment on this pull request for a long time and it made me believe that there's something left to do.

If bd is not useful enough to get merged into the main repository, I completely understand. However, I don't see any reason for this pull request to stay open for this long, if there is no chance for a merge.

**Comment by belak** [comment]
Thanks for your contribution! Unfortunately we're trying to focus on fixing bugs and improving existing modules rather than adding new ones at the moment. It's hard to keep everyone happy, but we're still doing our best to focus on the original goal of providing a sane set of defaults and a framework to build on rather than including every requested module.

I'm closing this for now because I think it would be a better fit for user configuration but thank-you for taking the time to submit this.

**Pull request closed without merging**
