### PR TITLE
Fixed slow performance with `alias git=hub`

### PR DESCRIPTION
**Pull request by jozefizso**
Prefixed all git calls with `command` so `alias git=hub` won't affect shell performance.

### CODE REVIEW

**Comment by devinrhode2** [comment]
hey @sorin-ionescu it seems that the 'new hub' is actually the same github/hub repository, still hub on homebrew. At the bottom of the readme on github/hub you can see "hub in ruby" (previous implementation) - also the latest commits (even by the creator of gh) are on the github/hub repo.

(also, sorry I commented on the wrong issue :/ )

**Comment by sorin-ionescu** [comment]
We can replace `git` with `command git` in Prezto. The last remaining code is the Git completion, which is already slow in Zsh and won't be fixed because the Zsh developers care more about correctness over usability and making completion go through `hub` will slow it down even if it's now compiled.

**Comment by PaBLoX-CL** [comment]
Sorry, what means correctnes over usability in this context?

**Comment by sorin-ionescu** [comment]
I don't remember. Google 'slow Zsh Git completion'.

**Pull request closed without merging**
