### PR TITLE
Add zstyle option to show pwd in long format

### PR DESCRIPTION
**Pull request by malikoth**
Alternative implementation to #1174.

### CODE REVIEW

**Comment by belak** [comment]
Anyway, sorry about the bikeshedding but I'd like to avoid changing setting names in the future if possible.

`long-pwd` (current), `full-pwd`, and other options may be preferable.

What are everyone's opinions on those?

**Comment by malikoth** [comment]
Certainly, getting a good variable name to avoid arbitrary changes to it later can only be a good thing, so I support spending some time seeing what people like.

Personally, I don't care what it's called.  I just want the option to be there!

It's worth noting that I could also use `zstyle -T` instead of `zstyle -t` to test for a variable named something like `short-pwd` as the condition for the line that shortens the pwd.  This would preserve the short form as the default if no zstyle is set, so that the default behavior does not change.

**Comment by indrajitr** [comment]
> Anyway, sorry about the bikeshedding but I'd like to avoid changing setting names in the future if possible.

Agreed totally!

That said, `full-pwd` might imply expanding `$HOME` to `/home/username` instead of just `~`. In that sense, `long-pwd` sounds marginally better in this particular case :)

**Comment by belak** [comment]
Alright, this seems good then. Thanks for your contribution!

**Comment by malikoth** [comment]
So @belak, @indrajitr brings up a good point...  Sorry to do this right after merge, but ...

Should `long-pwd` be replaced with a variable like `pwd-length` that can contain one of `short`, `long`, or `full`?  It might be nice to make it possible to expand the `$HOME` part of the pwd...

**Comment by belak** [comment]
That would be useful and would be easier to expand in the future.

**Pull request merged**
