### PR TITLE
add "--human-readable" in ls alias

### PR DESCRIPTION
**Pull request by YurixAnd**
Improves output of ls

### CODE REVIEW

**Comment by dlucian** [comment]
would not work for me:

```shell
~/Homestead ❯❯❯ ls --human-readable                                                                                                 ⏎ master ◼
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

**Comment by belak** [comment]
I don't want to merge this in if it breaks things on some platforms. It may be possible to use `-h` or something else though... or improve the check for GNU coreutils... since dircolors is available on OSX as well which seems to use the BSD versions of most commands by default.

**Comment by belak** [comment]
@dlucian What platform are you on where that didn't work for you?

**Comment by sorin-ionescu** [comment]
@belak It's fine. It's only set when GNU Coreutils `ls` detected.

**Comment by belak** [comment]
I'd rather not merge this, as it could get us into a situation where the default alias doesn't allow all options to be overridden as there's not a `--no-human-readable` flag I'm aware of. There was recently another PR where we removed a flag for diff like this because it made certain operations impossible without using `\diff` and I'd like to avoid a similar situation here.

Thank-you for the idea, but I think this may be a better fit if you want to put this in your own zshrc or look into adding it to some of the ls aliases we have defined.

**Pull request closed without merging**
