### PR TITLE
Fix sorin prompt double expansion

### PR DESCRIPTION
**Pull request by belak**
Refs #1267

This is fairly easy to reproduce with the https://github.com/njhartwell/pw3nage repo.

That being said, I think how this prompt actually goes about handling the git info is probably ripe for other injection issues. A more complete fix would probably be good at some point.

### CODE REVIEW

**Comment by samcv** [comment]
Just noticed this vulnerability today in the tickets. Tested the the patch and it works. Please merge this ASAP. Further changes can be done later but this is quite important as it's the default prompt.

**Comment by belak** [comment]
The main problem with this patch (and why I didn't just blindly merge it) is that as far as I can tell it just shifts the issue somewhere else. It would still be fairly easy to craft a branch name with single quotes which worked around this "fix". Really, the way this cache file is done isn't very good and that's a part of the problem.

**Comment by samcv** [comment]
Maybe I'm not understanding in which function/file it's actually getting expanded? If I make a weird branch name and just set:
```
  zstyle ':prezto:module:git:info:keys' 'format' 'status' '%b %p %c %s%A%B%S%a%d%m%r%U%u'
```
Then it shows the error is in `prompt_sorin_git_info:14: command not found: echo_hi` (for branch `$(echo_hi)`.

This line shows: [`zle && zle reset-prompt`](https://github.com/sorin-ionescu/prezto/blob/60c433d4ce680ddb2ca899b460e3714728cb221c/modules/prompt/functions/prompt_sorin_setup#L49).

**Comment by belak** [comment]
It's in a cache file. The `source "$_prompt_sorin_precmd_async_data"` line loads it by sourcing it.

**Comment by samcv** [comment]
Oh no… :-(

**Comment by belak** [comment]
Closed in favor of #1361

**Pull request closed without merging**
