### PR TITLE
Make ssh-add use $SSH_ASKPASS

### LINKED ISSUE #1320: SSH module asks for passphrase (ksshaskpass)
With `SSH_ASKPASS=/usr/bin/ksshaskpass`, get asked for my passphrase. The SSH module currently invokes ssh-add like that, so i open a shell to the “Enter passphrase” prompt with it active:

```console
$ ssh-add
Enter passphrase for ~/.ssh/id_rsa:
```

But when invoked without a terminal attached to stdin, `ssh-add` invokes ksshaskpass:

```console
$ ssh-add </dev/null
```

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #1320

## Proposed Changes

- Make `ssh-add` use `$SSH_ASKPASS` instead of using terminal input

### CODE REVIEW

**Comment by belak** [comment]
Thanks for your contribution! I've been playing around with this without setting SSH_ASKPASS and it still seems to work alright.

**Comment by flying-sheep** [comment]
great!

**Comment by crivotz** [comment]
I noticed that at each ssh session I was prompted for the passphrase.
I've removed the changes made by @flying-sheep and everything is back to work properly (passphrase required only once).
To make it work with the edit I had to install `ssh-askpass`

Can be a good thing add it to the module readme?

**Comment by indrajitr** [comment]
Yes, good idea. A PR would be appreciated :)

**Comment by crivotz** [comment]
No problem for PR but am I the only one that encountered this type or problem?

**Comment by indrajitr** [comment]
I am guessing the problem might be existing, just that most are not encountering it either because of the workflow ('x11-ssh-askpass' or a variant is already installed) or is on macOS or ssh module isn't enabled.
I am usually on macOS where this doesn't happen. And I frequently ssh into Arch Linux, Ubuntu etc. but I don't have prezto there.

**Comment by crivotz** [comment]
@indrajitr thanks. I will do the PR. Just for  information I am on Debian

**Comment by crivotz** [comment]
PR #1408 created. Thanks

**Pull request merged**
