### PR TITLE
Add alias-tips plugin

### PR DESCRIPTION
**Pull request by jedahan**
I really like [the alias-tips plugin](https://github.com/djui/alias-tips), thought other people might too

### CODE REVIEW

**Comment by Eriner** [comment]
I can't speak for anyone else, but this would drive me mad.

**Comment by liujoey** [comment]
Pleeeeeeeeeeeeeeeeeeease add this! Prezto added so many great alias, but it really lack of a great alias reminder!

I couldn't remember how may times I have to go back to this repo just searching for alias defined in various modules.

**Comment by diraol** [comment]
@liujoey you may just add this alias to a 'rc' file:
`alias sa='alias | grep -i'`
and then do `sa git` or `sa log`, for example.

**Comment by belak** [comment]
Interestingly enough, we already include `alias sa='alias | grep -i'` in the `utility` module. 😄

**Comment by liujoey** [comment]
@diraol @belak Thank you! Partially solved my headache.

But @belak comment is exactly the point, if alias-tips is included, then @diraol would find out that alias `sa` had been included already. 😄

**Pull request closed without merging**
