### PR TITLE
Add pyenv version to python-info

### PR DESCRIPTION
**Pull request by leoj3n**

### CODE REVIEW

**Comment by jeeftor** [comment]
Doesn't this functionality already exist?

**Comment by leoj3n** [comment]
@jeeftor Does what already exist? What do you mean by "this"?

**Comment by jeeftor** [comment]
I meant wasn't there already `pyenv` support in the model.  What you want is to basically get the current version regardless of whether you are in a virtual environment? 

As long as its not a performance hit i don't see an issue with the patch (except you need to resolve your conflicts) :)

**Comment by leoj3n** [comment]
No, this was added to make pyenv version info available to the prompt.

```
❯ pyenv version
system (set by /Users/leoj/.pyenv/version)

❯ python --version
Python 2.7.13
```

**Comment by belak** [comment]
Would it make more sense to just get the version info from the python executable in the path? Or maybe when we're in a virtualenv as well?

I guess the main question for me would be "when is this information important to show in a prompt?"

**Comment by belak** [comment]
I've closed this in favor of the version included in master which gets the information from the `python` executable on the path.

If you want to update it to include support for pyenv, an updated PR would be welcome. Thanks for the idea!

**Comment by belak** [comment]
I actually just pushed a new commit to add support for pyenv. Thanks for your contribution!

**Pull request closed without merging**
