### PR TITLE
Git GPG signatures

### PR DESCRIPTION
**Pull request by abstractj**
Good morning guys, I've been using it in my daily basis and I think it can be handy to Git module. This pull request include aliases to verify and create digital signatures with Git + GPG.

### CODE REVIEW

**Comment by abstractj** [comment]
I'm closing this issue, due to the lack of feedback. Feel free to get the code if you still think it makes sense

**Comment by belak** [comment]
Hi! Sorry this slipped past us. It's been hard for me to get motivated to go through old PRs lately. This looks good to me and seem useful.

I'm a little stuck on this:

```
alias gcS='git commit -S'
alias gpS='git show --pretty=short --show-signature'
```

At least in my opinion gcS should be the latter... but then I'm not 100 sure what to do with the first one. Maybe gc -S is short enough?

**Comment by belak** [comment]
On a side note, I'd be happy to manually apply this (I know there are conflicts) once we figure out what should go in. :)

**Comment by belak** [comment]
Thanks! I've also pushed documentation in eee3c9c (along with changing gpS to gcsS).

**Pull request merged**
