### PR TITLE
Add fasd as an external module

### LINKED ISSUE #780: fasd module requires fasd to be installed?
Hi there, 

I checked the [README](https://github.com/sorin-ionescu/prezto/tree/master/modules/fasd) and have a question about the following:

> The Prezto Fasd configuration differs from the default. The default aliases have been disabled

Does this mean that I don't have to install the default fasd package from my distribution's repository?

I followed the steps and added fasd after the completion module. However, the shortcut `j` does not work.

Excerpt of my `~/.zpreztorc`:

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'fasd' \
  'git' \
  'prompt' 
```

### PR DESCRIPTION
**Pull request by kaluzki**
Will fix #780

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
`fasd` comes with a variety of package managers; so, do many other directory jumping scripts. I'm inclined to reject this unless someone gives me a really good reason.

**Comment by jeffwidman** [comment]
Agree with @sorin-ionescu - I'd prefer that prezto doesn't include fasd by default--rather install/manage it externally with `homebrew`, `yum`, etc

**Comment by dryvenn** [comment]
If I may, I have a reason for this.
Sometimes I SSH onto a server where:
- my dotfiles are synced by NIS, so I expect to have my complete usual setup;
- fasd is not installed and I don't have root privileges to change that.

It is very frustrating indeed to use `j` repeatedly because of one's mnemonic memory and to get an error every time.

**Comment by belak** [comment]
This seems like a reasonable change to me... avoiding an external dependency would make it easier to deploy this everywhere.

Alternatively, we could fall back to using the external module if the fasd command doesn't exist...

**Comment by sorin-ionescu** [comment]
Actually, I was thinking of removing this in favour of z. It seems overkill. I only use it for directory changes.

**Comment by malikoth** [comment]
lol  I have an `alias z='fasd_cd'` in my config because I don't need the advanced functionality much, either.

**Comment by belak** [comment]
I'm going to merge this for now and update it to fall back to using the submodule.

Removing it entirely should be a separate issue.

Thanks for your contribution!

**Comment by belak** [comment]
The additional change is in 04bfb51.

**Pull request merged**
