### PR TITLE
ssh: update README to reflect macOS changes

### PR DESCRIPTION
**Pull request by slarew**
## Proposed Changes
  - Remove statement in README of SSH module that states the module won't load on macOS.

### CODE REVIEW

**Comment by indrajitr** [comment]
This seems to be related to #1394. @slarew, would you consider merging the two PR's into a single one?
We haven't done this consistently so far, but it might be useful to have README (or related doc update) together with the actual code change.

**Comment by belak** [comment]
Normally when we do doc updates later, it's because we missed the doc update. It would be good to see these in the same PR if they're related.

**Comment by slarew** [comment]
This commit is partially related to #1394, but it's actually more of a fix for 658fffb3a67a1f951d9c413802844694359caa7e when the README wasn't updated.

**Comment by belak** [comment]
That makes sense. Thanks for the clarification!

**Pull request merged**
