### PR TITLE
Better TTY logic for zlogin and zlogout

### PR DESCRIPTION
**Pull request by leoj3n**
Handles more cases more gracefully.

### CODE REVIEW

**Comment by facastagnini** [comment]
Hi @leoj3n , your PR got merged in the community maintained fork of this repo.

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

Your contribution is greatly appreciated!

https://github.com/zsh-users/prezto

**Comment by belak** [comment]
Thanks for your contribution! What's the advantage of using -o INTERACTIVE over -t 0? It seems like they both accomplish similar goals in different ways.

**Comment by jeffwidman** [comment]
Nudge @leoj3n

**Comment by leoj3n** [comment]
@belak `-t 0` could be a non-interactive terminal.

**Comment by belak** [comment]
This makes sense. Sorry it's taken me so long to get around to merging it!

Is there any reason to check -t 2 as well as -o INTERACTIVE? It seems like checking if the terminal is interactive would be enough.

**Pull request merged**
