### PR TITLE
Add support for pacaur

### PR DESCRIPTION
**Pull request by imcvampire**
## Proposed Changes

  - Add support for pacaur as alias for pacman

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
The file is empty except for a comment in the wrong language. Look at yaourt.zsh.

**Comment by belak** [comment]
It's been a week since this was initially posted and it doesn't look like there have been any additional updates. I'm closing this for now, but feel free to open a new PR when you've added code for this.

**Comment by oblitum** [comment]
Would be cool to have this option, it seems anything but yaourt is being recommended for AUR packages lately (IIRC due to security concerns), but Prezto ends up endorsing its use.

**Comment by belak** [comment]
It should already work to specify `pacaur` as an option. I've updated the README to prefer pacaur over yaourt and mention the security issues.

**Comment by oblitum** [comment]
OK, thanks for the info.

**Pull request closed without merging**
