### PR TITLE
Add Elixir and Phoenix framework module

### PR DESCRIPTION
**Pull request by tieubao**
Many developers adopt Elixir and Phoenix Framework and have built a great community. I found that adding Elixir and Phoenix support is a good fit with prezto. This will benefit lots of people.

The PR is strictly following the Contribution Guideline and also trying to align with Ruby and Rails module.

Please help to review

### CODE REVIEW

**Comment by belak** [comment]
Hi @tieubau! Thanks for taking the time to submit this.

A few quick comments:

* Please avoid one or two character aliases if possible. Git has a 1 character alias because of how common it is, but *very* few others should. 
* I'm not very familiar with Elixir or Phoenix but I like to see multiple people interested when adding a new module. 

With those things, there's a much better chance it's accepted.

**Comment by hieuphq** [comment]
👍

**Comment by thminhVN** [comment]
+1

**Comment by belak** [comment]
As long as the 1 and 2 character aliases are changed, this looks fine to me.

**Comment by tieubao** [comment]
@belak 👌

**Comment by belak** [comment]
This was merged in our temporary contrib repo as https://github.com/belak/prezto-contrib/commit/2666abb88c02baf99d7b694e9f3bfad89acdbfcc

I've kept the author information for attribution and when we find a permanent home for contrib, your changes will be included there as well.

**Comment by daveed-al** [comment]
nice 👍

**Comment by belak** [comment]
I'm going to close this for now since it was merged into the contrib repo. Thanks for your contribution!

**Pull request closed without merging**
