### PR TITLE
ssh: update SSH_ASKPASS workaround to more closely match what ssh-add needs

### LINKED ISSUE #1478: SSH module still asks for the passphrase
#1320 resurfaced, as #1408 immediately broke what i fixed in #1334.

the `</dev/null` was there for a reason (explained in #1320)

### PR DESCRIPTION
**Pull request by belak**
Fixes #1478 (and possibly supersedes #1479)

Note that I haven't been able to test this since I'm currently on a Mac. If anyone can confirm this fix works, I'd be happy to merge it in.

Also note that I don't think checking the OSTYPE is needed, as in other environments, DISPLAY wouldn't be set, and that mirrors what ssh-add is looking for.

### CODE REVIEW

**Comment by flying-sheep** [comment]
> and possibly supersedes #1479

definitely, thank you!

**Comment by belak** [comment]
Can you confirm that this fix works for you? I'm not as familiar with this module since I don't personally use it.

**Comment by flying-sheep** [comment]
yes, it does! thanks again

**Comment by belak** [comment]
Alright, it's been merged. Thanks for filing the issue!

**Comment by crivotz** [comment]
Hi, just for history with #1334 shell no longer asks for the passphrase you must install _ssh-askpass_
In #1408 I tried to fix it for those who do not use ssh-askpass

Now I tested with and without _ssh-askpass_ in both case no _X11_ windows is open and works fine.

**Comment by flying-sheep** [comment]
NP, i should have checked and reviewed your PR, then it could have fixed it for all 😄

**Comment by leshow** [comment]
I think I have gotten bitten by this. I log in to a bare terminal and start with `startx` on arch. Previously, after login I would be asked my ssh password, and then it was saved and I never got asked again.

I recently updated and my passphrase is no longer saved, I get prompted in the terminal each time

**Pull request merged**
