### PR TITLE
feat(history-substring-search): add `prefixed` setting

### PR DESCRIPTION
**Pull request by mritd**
add `HISTORY_SUBSTRING_SEARCH_PREFIXED` env setting to allow search matched against the start of each history entry

Signed-off-by: mritd <mritd@linux.com>

### CODE REVIEW

**Review by indrajitr — APPROVED** [review]
LGTM

**Comment by mritd** [comment]
@indrajitr 
I noticed that prezto refers to the v1.0.2 version of zsh-history-substring-search, but zsh-history-substring-search has been updated on the master branch, and it has not released a release version for a long time;

So, do we need to switch to the master branch?

**Comment by mritd** [comment]
Is there any progress?

**Comment by indrajitr** [comment]
We usually resist referencing untagged versions (`master` in this case) unless we absolutely have to.
Awaiting resolution of zsh-users/zsh-history-substring-search#129.

**Comment by brainsik** [comment]
👋 [v1.1.0 of zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search/releases/tag/v1.1.0) was released a few weeks ago. Can we re-open this?

**Comment by indrajitr** [comment]
Reopening this as v1.1.0 of history-substring-search has been applied.

**Comment by indrajitr** [comment]
Cherrypicked in #2060. Thanks @mritd!

**Pull request closed without merging**
