### PR TITLE
fix url pastes for zsh 5.1

### PR DESCRIPTION
**Pull request by Eriner**

### CODE REVIEW

**Comment by Eriner** [comment]
Fixes issue https://github.com/sorin-ionescu/prezto/issues/978

**Comment by sorin-ionescu** [comment]
Why are you closing your pull requests?

**Comment by Eriner** [comment]
I no longer have the time to support these, or make any changes to the PRs.

**Comment by sorin-ionescu** [comment]
It's not required of you to support bug fixes, enhancements, or revisions, only themes and modules if they are awfully complicated.

**Comment by Eriner** [comment]
To be more specific, I will no longer be making any changes to the PRs I have made here. I will not be contributing upstream (here) anymore. If there is an issue with any of the PRs I have made, I will not be making any revisions. Feel free to change them yourself as needed, but do not wait for me to respond/change them. 

I would like to submit my thanks to you for forking oh-my-zsh and creating Prezto.

**Comment by sorin-ionescu** [comment]
I get it. You're disappointed that I am not merging your pull-requests as quickly as you send them. Thank you for contributing.

**Comment by Eriner** [comment]
No, I am disappointed in the lack of commits for **5 months**, wherein you had enough time to respond, for example, ["All Git submodules are updated periodically"](https://github.com/sorin-ionescu/prezto/pull/932), but not enough time to do anything about it.

I am disappointed in the [half-truth in your commitment to increase activity](https://github.com/sorin-ionescu/prezto/pull/922), a premise on which I invested a significant amount of my time.

I am disappointed in the [poor handling](https://github.com/sorin-ionescu/prezto/pull/939) [of merges](https://github.com/sorin-ionescu/prezto/pull/922) that you actually *have* made.

**Comment by sorin-ionescu** [comment]
I commit locally but I don't push until I've used said commits for a while. I presently have 32 branches. That has always been the policy, and it's how I've kept the issue count low. There have been few breaking changes. This is not the first 5-month, no push streak. There have been others in the past.

Yes, I handled that merge poorly. I close cherry-picked commits/rebased branches with the following command, which failed since I've added descriptions to branch names, not just **pull/1015** but **pull/1015-fix-url-pastes**. It was 2 in the morning and chose sleep over reading  `man zshexpn` to fix it, and I will choose sleep again in the future.

```zsh
ghi close "${$(git-branch-current)##(pr|pull|issue)/}" -m "Merged via $(git log -1 --pretty=format:%h)."`
```

You are emotionally invested in Prezto; don't be. Here's what I did not do while explaining myself: commit.

**Comment by derimagia** [comment]
If you have a high enough version of zsh, I recommend using https://github.com/zsh-users/zsh/blob/master/Functions/Zle/bracketed-paste-url-magic (See http://www.zsh.org/mla/workers/2015/msg02610.html) - It doesn't lag when you paste.

**Comment by Eriner** [comment]
@derimagia thanks for the info! The zsh version to check against is 5.2. I think 5.1.1 may also work, but I vaguely remember an issue that had to be worked around for that version, so I think targeting `is-at-least 5.2` is the best bet.

**Comment by belak** [comment]
Ok, so bracketed-paste, bracketed-paste-magic, and bracketed-paste-url-magic all seem useful. I think a PR that adds those with the correct version checks would be reasonable to me. Feel free to ping me if you get around to updating this PR or opening a new one and I'll take a look.

**Comment by Eriner** [comment]
See: https://github.com/Eriner/zim/pull/160

**Pull request closed without merging**
