### PR TITLE
general: Reformat documentation with better formatting and wording

### PR DESCRIPTION
**Pull request by indrajitr**
General purpose reformating and rewording in (a few places). This should also make markdown linting happier.
 
Prefer back-ticks wherever useful and use `console` for code blocks to be executed on terminal.
 
Also, update references links wherever possible (including update from 'http://' to 'https://').

### CODE REVIEW

**Comment by jeffwidman** [comment]
I think as a general rule it'd be better to wait a few days for another maintainer to review before merging, and then maybe nudge comment. I realize this is just formatting and slight rewording changes, but even so I've seen many such PR's over the years on various projects that ended up benefiting from code review. And given that it's formatting/docs, it's not like this has to be merged _immediately_. 😀 

Additionally, beyond spotting typos etc, it also keeps the project's collaborative culture by giving the rest of us a chance to ask questions and learn so that in the future we better understand how to format stuff (perhaps you used a nifty markdown trick in here I don't know...).

Anyway, no need to revert or anything, but just in general can we aim for that unless it's a time-sensitive bugfix? 

Lastly, thanks for the hard work here, I think the formatting looks a lot better in general. 👍 

cc @belak

**Comment by jeffwidman** [comment]
Hah, just saw @belak 's comment on https://github.com/sorin-ionescu/prezto/pull/1915#issuecomment-832887368 about merging w/o waiting on doc changes. 

I think in general, waiting at least 48 hours is probably okay... a minor typo fix makes sense, but something that touches > 1K LOC, even if it's only docs changes, well, I'd certainly feel a little better if there was a second set of eyes on it...

**Comment by indrajitr** [comment]
> I think in general, waiting at least 48 hours is probably okay... a minor typo fix makes sense, but something that touches > 1K LOC, even if it's only docs changes, well, I'd certainly feel a little better if there was a second set of eyes on it...

Yep, agreed 💯 
In general, at least having few more pairs of eyes (and at least one review approval) is always useful. That's what I usually follow (unless it is a trivial one, or has a bug). This one was sitting for a couple of days, and I didn't notice that you actually didn't approve this one when you approved the other ones _en masse_ a few hours ago :)

**Comment by jeffwidman** [comment]
Hah, so you totally did wait 2 days! I missed that, I guess I'm just that far behind in my email. 😀

**Pull request merged**
