### PR TITLE
adds a Taskwarrior module

### PR DESCRIPTION
**Pull request by bgrrtt**

### CODE REVIEW

**Comment by leoj3n** [comment]
Can you explain what this does? Looks interesting.

**Comment by sbadia** [comment]
From tw website:  https://taskwarrior.org/

> Taskwarrior is Free and Open Source Software that manages your TODO list from the command line.

This PR install the taskwarrior completion file from Johannes Schlatow and P.C. Shyamshankar, and create an alias `t`.

**Comment by sbadia** [comment]
Hi @facastagnini, we can add this one on https://github.com/zsh-users/prezto/issues/1 ?

**Comment by facastagnini** [comment]
sure, let me add it to the list, we will review it asap

**Comment by sbadia** [comment]
thanks!!

**Comment by belak** [comment]
Is there any way the _task completion file could go in the zsh-completions repo? Because that's the largest part of this module (and the other part is aliasing task to t) I'd rather not merge this when the biggest part might fit better somewhere else and a single letter alias is a pretty big thing to include.

**Comment by jeffwidman** [comment]
This feels a bit niche and (at least right now) I'd also prefer not to see it merged. Makes a lot of sense to see if it can be added to the zsh-completions though.

**Comment by bgrrtt** [comment]
Yea, that totally makes sense. TaskWarrior is pretty niche, I just wanted an easy way to use it and was learning how to work with dotfiles and Github. I'm happy to not include it as a module, thanks for the discussion!

**Comment by belak** [comment]
Thanks for taking the time to contribute! Hope to see other submissions later ;)

**Pull request closed without merging**
