### PR TITLE
Update pure prompt to v1.5.2

### PR DESCRIPTION
**Pull request by Plastix**
This fixes a security issue with malicious branch names

### CODE REVIEW

**Comment by janclarin** [comment]
Is this necessary? When installing prezto, the latest versions of the submodules are pulled from their respective GitHub repos. I have the latest version of pure after installing it.

**Comment by Plastix** [comment]
That is incorrect. When doing a `git clone --recursive https://github.com/sorin-ionescu/prezto.git` `sindresorhus/pure@fb4c37dad3c5cbdebca61a8ff5545397c11d450f` is checked out.

You most likely updated your submodules locally.

**Comment by janclarin** [comment]
Seems like I had already run `git submodule update --recursive` before checking with a fresh install, sorry for the confusion. Thanks for the clarification @Plastix.

**Comment by belak** [comment]
Thanks for your contribution! No reason to keep this out of date any longer.

**Pull request merged**
