### PR TITLE
Update ssh module for multi session hosts

### PR DESCRIPTION
**Pull request by mchataigner**
create ssh_agent_env with current user id in file name to avoid collisions with other users
create ssh_agent_sock with current user id in file name to avoid collisions with other users

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
`$TMPDIR` should be set to the user's temporary directory, not `/tmp`, the fail-safe; so, there should not be a collision.

You can use `$UID` instead of `id -u`.

**Comment by mchataigner** [comment]
Ok, I changed to UID instead of id -u.
So I agree with you that one should set TMPDIR, but if it is not set it will collide.
With this change it will never collide.
Thanks.

**Comment by sorin-ionescu** [comment]
Presto should set it for you.

**Comment by belak** [comment]
Thanks for your contribution!

**Pull request merged**
