### PR TITLE
Add Elapsed time module

### PR DESCRIPTION
**Pull request by Salamandar**
Add a module Elapsed time, that prints the run time of commands, just like the Paradox theme, but for any theme !

The corresponding code could be removed from the Paradox theme.

### CODE REVIEW

**Comment by Salamandar** [comment]
This code could be updated, i.e to change the granularity (milliseconds) or to add a function that does not printf, but returns the string to be printed by the theme.

**Comment by belak** [comment]
Thanks for submitting this! Unfortunately, we're not currently accepting modules in prezto-core. However, if you want to re-submit this to [prezto-contrib](https://github.com/belak/prezto-contrib) we'd be happy to accept it there.

**Comment by Salamandar** [comment]
OK, gonna do that. :)

**Comment by indrajitr** [comment]
Actually, after thinking a bit about it, this functionality is after all just a zsh hook and probably doesn’t require a full blown module. 

Instead it could be refactored out into a common function (like `prompt-pwd`) and used by other themes.

**Comment by Salamandar** [comment]
Can you point to me an example ? I could do a PR too.
Also, I don't know if you saw it, but my PR was accepted is prezto-contrib.

**Pull request closed without merging**
