### PR TITLE
Added conda virtualenv support to python module.

### PR DESCRIPTION
**Pull request by egpbos**
Conda is both a package manager like pip (but without the tedious compilation, because binary) and an environment manager like virtualenv (inside conda environments one can still use pip, if necessary). I like it a lot better than pip+venv. This PR slightly modifies the python module to be compatible with Conda as well as virtualenv. Virtualenv support works as before, the only real changes are:
- when using conda, virtualenv things are not loaded, since the two cannot be used together (maybe they can, but I can't think of a reason why one would want this)
- when inside a conda venv, python_info[virtualenv] is set to the right conda environment name.

### CODE REVIEW

**Comment by belak** [comment]
I believe there were some changes to allow skipping of virtualenvwrapper init if an option is set, so that should probably be used, rather than the conda hacks here.

Could you provide a link to where CONDA_DEFAULT_ENV comes from? Based on that variable name, it sounds like it's a fallback and might not catch all cases, but you say it works... so maybe it's just not named very well?

Once that's done, I can take another look at merging this.

**Comment by egpbos** [comment]
I'll use zstyle for activating conda as well and rebase the whole branch to current master to include skipping of virtualenvwrapper.

I can't find any official documentation for CONDA_DEFAULT_ENV online. However, the command `conda info --all` lists it. Also, in the activate script that comes with any conda environment (try `less $(which activate)` if you have conda installed) you'll find the following:

```sh
    # CONDA_DEFAULT_ENV is the shortest representation of how conda recognizes your env.
    #    It can be an env name, or a full path.
    #    Last date of change: 2016-06-21
    # If the string contains / it's a path
    if [[ "$@" == */* ]]; then
        export CONDA_DEFAULT_ENV=$(get_abs_filename "$args")
    else
        export CONDA_DEFAULT_ENV="$args"
    fi
    # CONDA_PREFIX is always the full path to the activated environment.  It is not set
    #    when no environment is active.
    # Legacy support: CONDA_DEFAULT_ENV is either env name or full path if given as path.
    #    CONDA_PREFIX is always the full path, for consistency.
    #    Last date of change: 2016-06-21
```

**Comment by egpbos** [comment]
Ah, and, crucially, it also contains this:

```sh
    # if CONDA_DEFAULT_ENV not in PS1, prepend it with parentheses
    if [ $("$_CONDA_DIR/conda" ..changeps1) = "1" ]; then
        if ! $(grep -q CONDA_DEFAULT_ENV <<<$PS1); then
            if ! $(grep -q "POWERLINE" <<<$PS1); then
                export PS1="(${CONDA_DEFAULT_ENV}) $PS1"
            fi
        fi
    fi
```

That is: conda itself uses this variable to modify the prompt. That's actually how I think I found it :)

**Comment by egpbos** [comment]
To clarify, the conda part in modules/python/init.zsh doesn't actually do anything except check whether conda settings are correct. If not, it tells you how to set it so that it works (see the conda code in the comment above, conda checks for the changeps1 setting, so we use that to deactivate conda's own prompt changing). The real work is done in the python-info function, just like with virtualenvwrapper.

**Comment by egpbos** [comment]
Ok, done.

I also threw in some documentation for good measure :)

**Comment by kepbod** [comment]
Great PR! 👍

**Comment by belak** [comment]
Sorry it's taken me this long to get to this... so, this doesn't actually load conda? It just checks settings? Would it be worthwhile changing this so it *does* load conda?

**Comment by kepbod** [comment]
I tested it, and it works.

**Comment by egpbos** [comment]
Loading conda would be difficult to do automatically, since its installation location is often non-default (at least in my case, my preference changes regularly), sometimes it's installed system-wide, sometimes only for the user, etc. Ideally, conda itself would provide support for zsh. For bash it already adds the conda bin dir to $PATH in .bash_profile or .bashrc or something. Once conda is loaded in PATH, everything else is set, except the handling of the prompt, which is what I fixed in this PR.

**Comment by kepbod** [comment]
I really want this feature.

**Comment by belak** [comment]
Alright, once the conflicts are fixed, I think this will be ready

**Comment by belak** [comment]
Thanks for submitting this. It's been merged in #1505.

**Pull request closed without merging**
