### PR TITLE
Add virtualenv info to prezto paradox prompt

### PR DESCRIPTION
**Pull request by milin**
The paradox prompt was missing virtualenv info for python projects, so this pull request adds that.

virtualenv info for paradox theme

### CODE REVIEW

**Comment by milin** [comment]
@sorin-ionescu Any comments would be helpful regarding this. Have personally been using this patch for a few days with virtualenv support and it seems to be pretty stable.

**Comment by sorin-ionescu** [comment]
It looks fine; it has just a few white space issues — missing blank lines. Is `(e)` needed on variables?

Squash the commits.

**Comment by milin** [comment]
@sorin-ionescu looks like e is not needed, so I removed it. Added missing blank lines and squashed the commits into one.

**Comment by milin** [comment]
Anything else needed before merging @sorin-ionescu

**Pull request closed without merging**
