### PR TITLE
added "lean" prompt theme

### PR DESCRIPTION
**Pull request by sergiorussia**
## Proposed Changes

  - add https://github.com/miekg/lean.git prompt theme support

people that like minimal prompts could find this theme very appealing. i've used "pure" theme for some time, but two-line prompt is too spacious. i've added a bit of prezto integration documentation to lean README.md.
screenshot of how can it look like is here [https://imgur.com/IbNVB3M](https://imgur.com/IbNVB3M)

### CODE REVIEW

**Comment by sergiorussia** [comment]
@belak or @indrajitr could you take a look?

**Comment by belak** [comment]
I'm not sure what our plan is for themes. I'd like to avoid adding too many submodules... however, I like the theme and I agree that there's a certain lack of minimal themes included with prezto (I was considering merging the theme I keep in my dotfiles at some point which is roughly based on the default gentoo prompt).

I'm not sure what we'll decide on, but if this doesn't get merged in here, it seems like a great candidate for the contrib repo we've been discussing.

**Comment by sergiorussia** [comment]
the main motivation to add this theme was indeed the lack of minimal ones. most of existing themes are too bloated imo. the "pure" is closest to minimal among all, but for some reason it is 2-lines height... anyway, hope you'll merge this one, because some new users would be just scared by all those bells-n-whistles, funny prompt symbols etc while simply looking for zsh-with-prezto power and i'm pretty sure many of them would find "lean" just enough for their needs :)

**Comment by crivotz** [comment]
I like it :+1: 
Pure is cool but I also don't understand why of the two lines

**Comment by sergiorussia** [comment]
@belak any news? hanging pr is a bad pr, let's do something with it

**Comment by belak** [comment]
I'm waiting for one other PR to be reviewed and a discussion on what we want to put in our contrib repo. I haven't forgotten about this PR.

**Comment by sergiorussia** [comment]
hey @belak , any news? 2 weeks already

**Comment by belak** [comment]
Unfortunately, same news as before. Still waiting on other people to review #1458 (as it's a pretty important change to module loading and I don't want to break anything) so we can start work on a contrib repo. I'd like to avoid as much confusion as possible, for when we (potentially) move some of the prompts to a separate module in a different repo. Especially for submodules, which have their own problems - I'd like for most external prompts to be included in the contrib repo, rather than core.

I do appreciate you following up.

**Comment by sergiorussia** [comment]
@belak hi, i see that module loading PR was merged (finally). what should i do now? wait for zsh-contrib repo to be created and recreate this PR to that repo instead?

**Comment by crivotz** [comment]
In this case, I believe there is the problem discussed in this issue #1484

**Comment by belak** [comment]
This was added to an experimental contrib repo in https://github.com/belak/prezto-contrib/commit/c718baae18a397a8caa7838abdfa969f6c4573ae

**Comment by sergiorussia** [comment]
@belak, nice! so now i can use that repo with the recently merged changes in prezto, right? if so, should we cancel this PR?

**Comment by belak** [comment]
Yep, you should be able to clone contrib and enable the `contrib-prompt` module before the `prompt` module... then you should be able to load lean like normal.

I'm still deciding what to do with open PRs which are migrated to contrib. My plan is currently to tag everything which makes it into contrib and go back to close them when the contrib repo is moved to its home.

**Comment by sergiorussia** [comment]
@belak 
```
cd $ZPREZTODIR
zprezto-update
# up to date

git clone https://github.com/belak/prezto-contrib contrib
cd contrib
git submodule update --init --recursive
# submodules are fetched, everything is ok

cd $ZPREZTODIR
# manually added 'contrib-prompt' before 'prompt', then finally
git rm -f modules/prompt/external/lean

# reopened terminal, got
Couldn't read file /home/sergio/.zprezto/modules/prompt/functions/prompt_lean_setup containing theme lean.
```

huh? the file is in contrib!
```
ls $ZPREZTODIR/contrib/contrib-prompt/functions/prompt_lean_setup                                                  ~
/home/sergio/.zprezto/contrib/contrib-prompt/functions/prompt_lean_setup
```
README said "By default modules will be loaded from */modules* and */contrib*."

**Comment by belak** [comment]
Are you sure the main prezto repo is on the right branch?

**Comment by crivotz** [comment]
Works like a charm! Thanks good job

**Comment by sergiorussia** [comment]
@belak 
```
Couldn't read file /home/sergio/.zprezto/modules/prompt/functions/prompt_lean_setup containing theme lean.
% cd $ZPREZTODIR
%  git config --get remote.origin.url
git@github.com:sorin-ionescu/prezto.git
%  git branch
* master
%  git pull
Already up-to-date.
```

**Comment by sergiorussia** [comment]
oh, wait, seems like prompt_lean_setup was left as garbage, sorry :)

**Comment by sergiorussia** [comment]
woohoo, thanks for your question, made me check git status. removed garbage - now everything works :) let's close this PR

**Comment by belak** [comment]
Alright, sorry for not following up! Thanks for the original submission. I'm glad we could get it into contrib. :)

**Pull request closed without merging**
