### PR TITLE
add support for nodenv

### PR DESCRIPTION
**Pull request by seanzxx**
nodenv is a node version manager. 
This PR is used to initialize nodenv and to get node version for prompt. 

nodenv: https://github.com/wfarr/nodenv

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
It doesn't seem to be used by many people. I am reluctant to merge it.

**Comment by habitullence** [comment]
If you look at the nodenv repo, it doesn't look like it but comes out-of-the-Boxen, couldn't help myself, so probably quite few people use it, including myself and Github :+1:

**Comment by lotia** [comment]
The project to which @seanzxx is referring is a fork of https://github.com/nodenv/nodenv I'm not sure how popular the project is compared to nvm, but the ruby module has support for several version managers and it would be very useful to have support available in prezto.

**Comment by mkcode** [comment]
This project definitely will become more popular as time goes on. The interface for nodenv is consistent with rbenv, which is why it is nice.

GitHub is now defaulting to nodenv, so we can expect many people for follow shortly:

  https://github.com/github/homebrew-bootstrap
  https://github.com/github/homebrew-bootstrap/blob/master/cmd/brew-bootstrap-nodenv-node

**Comment by belak** [comment]
This was merged via PR #1276. Thanks for the contribution!

**Pull request closed without merging**
