### PR TITLE
Adding the ability to specify tmux session name.

### PR DESCRIPTION
**Pull request by guildencrantz**

### CODE REVIEW

**Comment by alerque** [comment]
:+1: for the functionality here. @guildencrantz are you interested in fixing the rc file per the comment above? @sorin-ionescu Is that all it would take to get this merged?

**Comment by sorin-ionescu** [comment]
That should be enough.

**Comment by guildencrantz** [comment]
Sorry for the delay.

**Comment by belak** [comment]
Merged in ddf5a99

**Pull request closed without merging**
