### PR TITLE
Port the oh-my-zsh gitignore plugin to prezto

### PR DESCRIPTION
**Pull request by 1989car**
The oh-my-zsh gitignore plugin can get gitignore template from [gitignore.io](http://gitignore.io)  .  It may be usefull for developers.

As the gitignore.io website says, they hosting 191 Operating System, IDE, and Programming Language .gitignore templates.

### CODE REVIEW

**Comment by belak** [comment]
I'm fairly hesitant to add this, as the feature is built into github, this depends on an external service, and there are gitignore templates available in https://github.com/github/gitignore.

Does anyone else have opinions on this?

**Comment by ezintz** [comment]
From my perspective this is not needed. I anyways to not like all the Git aliases that are already there. So to get this feature in my prezto/cli environment I would go with a different solution, also regarding to the docs of gitignore.io:

`git config --global alias.ignore '!gi() { curl -L -s https://www.gitignore.io/api/$@ ;}; gi'`

**Comment by belak** [comment]
Thanks for submitting this, but I'm closing this for now as I'm not sure it's a good fit for prezto right now.

**Comment by belak** [comment]
I just realized we also do something similar with github's url shortener... so this may actually be a decent fit... unfortunately it looks like the repo is gone, so I can't reopen this.

**Pull request closed without merging**
