### PR TITLE
Add a basic fzf module

### PR DESCRIPTION
**Pull request by ashishgandhi**
`fzf` is a very good fuzzy history completer among other things. Add a basic module to support it. Sets up a place to add more features from it in the future if we decide to.

### CODE REVIEW

**Comment by shwanton** [comment]
👍

**Comment by belak** [comment]
Thanks for your contribution. Unfortunately, we're currently avoiding new modules in the prezto core. However, I'd be happy to merge something like this in the contrib repo. https://github.com/belak/prezto-contrib

**Comment by belak** [comment]
Hi! Thanks for submitting this! I like the idea but we're also not really accepting new modules or prompts in the main repo. If you're still interested in getting this in, please feel free to submit it to the contrib repo (https://github.com/belak/prezto-contrib) and I'd be happy to merge it as a starting point for an fzf module.

**Comment by ashishgandhi** [comment]
I switch to managing my own Zsh now no longer use `prezto`. I am happy if someone else wants to run with this. It's not like super novel anything.

Stay away from COVID-19.

**Pull request closed without merging**
