### PR TITLE
Redirect `casks` to `brew search`

### PR DESCRIPTION
**Pull request by singularitti**
## Fixes
In most recent [brew](https://github.com/Homebrew/brew), calling `brew cask search` is deprecated.
It is suggested to use `brew search` instead.
See pull-request [#4316](https://github.com/Homebrew/brew/pull/4316) for details.

## Proposed Changes

  - Redirect `brew cask search` to `brew search` as suggested by Homebrew

### CODE REVIEW

**Comment by singularitti** [comment]
A possible way to solve #1595?

**Comment by dbernheisel** [comment]
I'm conflicted if this is the right way to go. I understand there's muscle-memory here, and this will rid the deprecation warning, but if Homebrew won't have "brew cask search" anymore then should we have an alias for it?

Or should it be replaced with something similar, but not functionally the same, like `brew cask search --casks`? (The difference here I think is that it's an offline search vs online search).

```
❯ brew search --help
                                                                                                                    
brew search, -S:
    Display all locally available formulae (including tapped ones).
    No online search is performed.

brew search --casks
    Display all locally available casks (including tapped ones).
    No online search is performed.

brew search [--desc] (text|/text/):
    Perform a substring search of cask tokens and formula names for text. If text
    is surrounded with slashes, then it is interpreted as a regular expression.
    The search for text is extended online to official taps.

    If --desc is passed, search formulae with a description matching text and
    casks with a name matching text.

brew search (--debian|--fedora|--fink|--macports|--opensuse|--ubuntu) text:
    Search for text in the given package manager's list.
```

**Comment by singularitti** [comment]
@dbernheisel That's a good idea. I was thinking about when users are typing `casks`, they are expecting only casks are listed out. But currently, Homebrew will use `brew search`, resulting in `casks` will print some `Formulae`. That's not intuitive, I would rather remember it and use `brews` next time.

**Comment by dbernheisel** [comment]
for what it's worth, the only thing I can come up with that is somewhat equivalent to an online search that's only casks is this:

```sh
$ brews chrome | sed -ne '/==> Casks/,$p'
==> Casks
chrome-devtools
chrome-remote-desktop-host
chromedriver
dmm-player-for-chrome
epichrome
google-chrome
google-chrome-beta
google-chrome-canary
google-chrome-dev
mkchromecast
```

But this loses all the formatting that brew gives. For example, I have chromedriver installed so I _should_ see it bolded with a checkmark

image

Maybe a `sed` or `awk` expert can help.

**Comment by singularitti** [comment]
Homebrew officially has a command line tool for doing similar things: [homebrew-aliases](https://github.com/Homebrew/homebrew-aliases).

**Comment by indrajitr** [comment]
We need to revisit the whole of `brew` and `cask` situation. Multiple `cask` subcommands have been unified into `brew` lately.

**Comment by singularitti** [comment]
> We need to revisit the whole of brew and cask situation. Multiple cask subcommands have been unified into brew lately.

That's the point.

**Comment by belak** [comment]
The fix in #1623 seems to do this and make it clear that these commands may not exist in the future. I'm going to close this for now since that PR does pretty much the same thing. Thanks for submitting this!

**Pull request closed without merging**
