### PR TITLE
history-substring-search: add fuzzy and unique

### PR DESCRIPTION
**Pull request by dllud**
Adds 2 useful options available on the currently linked version (`v1.0.2`) of history-substring-search: fuzzy search and unique results (removes duplicates).

### CODE REVIEW

**Comment by indrajitr** [comment]
Nice!

**Review by indrajitr — APPROVED** [review]

**Comment by jeffwidman** [comment]
Would it be a better out-of-the-box user experience to enable fuzzy search by default?

Unique I'm 👍 on adding the option, not so sure about enabling by default...

**Comment by dllud** [comment]
> Would it be a better out-of-the-box user experience to enable fuzzy search by default?

I don't think so. It drastically changes the results you get when using spaces.
Currently users are expecting a search for `ls -` to return the previous ls commands where arguments were used. With fuzzy search enabled they would get that plus all commands where `ls` was followed by any directory that had a `-` in it's name.

**Comment by indrajitr** [comment]
I am applying them as-is. Minor tweaks to follow.

**Pull request merged**
