### PR TITLE
Add module alias-tips

### PR DESCRIPTION
**Pull request by N4M3Z**
Introduces support for external module [djui/alias-tips](https://github.com/djui/alias-tips).

### CODE REVIEW

**Comment by belak** [comment]
Hello, unfortunately we're trying to avoid any new modules in prezto-core, especially those with external dependencies. If you're willing to submit it elsewhere, it would probably be a better fit for the [prezto-contrib](https://github.com/belak/prezto-contrib) repo.

**Comment by N4M3Z** [comment]
Hi @belak. Your point makes sense, I'll make a pull request to the contrib repository. I have about 5 more modules to contribute. I left Prezto for Zplug about about a year ago exactly because I was missing specific modules. The contrib folder is a good solution. Is the prezto team currently planning to move to a different way of organizing the project and modules?

**Comment by belak** [comment]
This was submitted to contrib in https://github.com/belak/prezto-contrib/pull/10

**Comment by belak** [comment]
This was submitted to the contrib repo, as mentioned above. Thanks for doing that by the way!

**Pull request closed without merging**
