### PR TITLE
Fix unarchive for .deb which uses xz, and absolute paths

### PR DESCRIPTION
**Pull request by zachriggle**

### CODE REVIEW

**Comment by zachriggle** [comment]
Why'd this get closed?

**Comment by sorin-ionescu** [comment]
It got merged.

**Comment by Eriner** [comment]
@sorin-ionescu If you're going to cherry-pick and just close PRs, at the very least, close it referencing the cherry-pick commit. Otherwise you're going to create a history nightmare.

**Comment by sorin-ionescu** [comment]
Merged in 7227c4f0bef5f8ae787c65150d7a7403394fff48.

**Pull request closed without merging**
